name: Benchmark v2 Scheduled Runner - MI325 Single-GPU

on:
  schedule:
    # Run daily at 16:30 UTC
    - cron: "30 16 * * *"
  push:
    branches:
      - run-benchmarking-gh-actions*

jobs:
  benchmark-v2-default:
    name: Benchmark v2 - Default Models
    uses: ./.github/workflows/benchmark_v2.yml
    with:
      runner: amd-mi325-ci-1gpu
      warmup_iterations: 3
      measurement_iterations: 5
      num_tokens_to_generate: 100
      commit_sha: ${{ github.sha }}
      upload_to_hub: true
      run_id: ${{ github.run_id }}
      benchmark_repo_id: optimum-amd/transformers-daily-benchmarks
    secrets: inherit