name: Upload PR Documentation

on:
  workflow_run:
    workflows: ["Build PR Documentation"]
    types:
      - completed

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/upload_pr_documentation.yml@main
    with:
      package_name: transformers
    secrets:
      hf_token:  ${{ secrets.HF_TOKEN }}
      comment_bot_app_id: ${{ secrets.COMMENT_BOT_APP_ID }}
      comment_bot_secret_id: ${{ secrets.COMMENT_BOT_SECRET_PEM }}
